# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b6opuXslr1fxZUsZNj-sYY_CSV5Rnlp8
"""

import plotly.graph_objects as go

fig = go.Figure()
fig.add_trace(go.Scatter(x = [1,2,3,4,5], y = [3,4,5,6,7], mode = 'markers'))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter(x = [1,2,3,4,5], y = [3,4,5,6,7], mode = 'lines'))
fig.show()

fig = go.Figure()
fig.add_trace(go.Bar(x = [1,2,3,4,5], y = [3,4,5,6,7]))
fig.show()

x = [1,1,12,22,3,2,2,3,3,4,4,5,5,12,13,31,3,45,6,7,6,7]
fig = go.Figure(data = go.Histogram(x =x))
fig.show()

import seaborn as sns

tips = sns.load_dataset('tips')

fig = go.Figure(data = [go.Histogram(x = tips.total_bill)])
fig.show()

tips

fig = go.Figure()
fig.add_trace(go.Scatter(x = tips.total_bill,y = tips.tip, mode = 'markers' ,marker_size = 10*tips['size']))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = tips.total_bill, y = tips.tip, mode = 'markers' ,z = tips['size']))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = [1,2,3,4,5], y = [4,5,6,7,8], mode = 'lines' ,z = [3,4,5,6,7]))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = [1,2,3,4,5], y = [4,5,6,7,8], mode = 'markers' ,z = [3,4,5,6,7]))
fig.show()

fig = go.Figure()
fig.add_trace(go.Scatter3d(x = tips.total_bill, y = tips.tip, mode = 'lines' ,z = tips['size']))
fig.show()

